import axios from "axios";
import Discord from "discord.js";
import { memberHasOneRole } from "../modules/utils";
import embeds from "../modules/embeds";


export default {
    execute: async (interaction: Discord.CommandInteraction, throwError: (title: string, desc?: string) => Discord.Message) => {
        if (!(interaction.member instanceof Discord.GuildMember)) return throwError("Oops!", "Something went wrong. Please try again later.")
        if (!memberHasOneRole(interaction.member, (process.env.ADMIN_ROLES ?? "").split(" "))) return throwError("Access denied", "You're not permitted to do that.")

        await interaction.deferReply({ ephemeral: true })

        var res;
        try {
            res = await axios.get(
                `https://loader.cypherauth.com/resellerpanel/restAPI.php?apiKey=${process.env.API_KEY}&type=reset&license=${interaction.options.get("key")?.value}`, {
                headers: {
                    "User-Agent": "backendserver"
                }
            })
        } catch (err) {
            throwError("Oops", "Something went wrong! More information about error in console.")
            return console.log(err)
        }
        console.log(`GET to ${res.config.url} with status code ${res.status}.`)

        if (res.data?.success) {
            interaction.editReply({
                embeds: [
                    embeds.success("Success", `The license (\`\`${interaction.options.get("key")?.value}\`\`) was reset successfully.`)
                ]
            })
        } else {
            throwError("Error", `License reset attempt is failed: \`\`${res.data.message}\`\`.`)
        }
    },
    data: new Discord.SlashCommandBuilder()
        .setName("reset")
        .setDescription("Reset the license by key (through API).")
        .addStringOption((opt) =>
            opt
                .setName("key")
                .setDescription("license key generated by you")
                .setRequired(true)
        )
        .toJSON()
}